apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: nayanzagade7@gmail.com.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          region: ap-south-1
          hostedZoneID: Z005920810ULG86JXT8IA
          # cert-manager uses the AWS role via OIDC (no access key needed)
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cd-cert
  namespace: argocd  
spec:
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - argocd.nayanzagade.xyz            